//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.544
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace CGME
{
	public class GameBuilder
	{

		private static CGME.Game game = null;
		
		private static List<Card> card_list = new List<Card>();
		
		//private static Ruleset Ruleset ;

		public GameBuilder ()
		{

		}
		public static CGME.Player AddPlayer(CGME.Player player){// BUILDING PLAYERS
			//CGME.Player game_player = Factory.BuildPlayer(name, enable);
			return game.AddPlayer (player);
		}
				
		public static CGME.Phase AddPhase(CGME.Phase phase){
			game.AddPhase (phase);
			return phase;
		}
		
		public static CGME.Action AddAction(CGME.Action action, string phase ){
			return game.GetPhase(phase).AddAction(action);
		}
		
		public static CGME.Game Build(){
		
			// BUILDING THE GAME TABLE
			game = new CGME.Game();

			// BUILDING PHASES
			AddPhase (new Phase("Play Phase"));
			
			// BUILDING ACTIONS
			
			Action pass =  new ActionEndPhase("End Phase");
			ActionConditionWaitForInput play_wait = new ActionConditionWaitForInput("Pass",pass);
	
			game.GetPhase("Play Phase").AddAction (play_wait);
					
			// BUILDING PLAYERS
			AddPlayer (new Player("Game Player"));
			
			AddPlayer (new Player("Human Player"));

			// BUILDING DECKS
			game.GetPlayer("Human Player").AddDeck(new Deck("Draw Pile"));
		
			// ADDING RESOURCES
			game.AddResource(new ResourceNumber("Life Points",30), "Human Player");
			game.AddResource(new ResourceNumber("Life Points",30), "Game Player");
			game.AddResource (new ResourceNumber("Victory Points", 0), "Human Player");
			
			// BUILDING CARDS
			card_list.Add(new Card("Dwarf Dork",false));
			
			// BUILD DECKS
			for (int i = 1; i <= 2; i++){	
				Card new_card = card_list[0];
				new_card.AddResource(new ResourceText("Description", "Drunk and Smelly"));
				new_card.AddResource(new ResourceAction("Play Phase",new ActionAttack("Attack")));
	
				game.GetPlayer ("Human Player").GetDeck ("Draw Pile").AddCard(new_card);
			}
					
			return game;
		}
	}
}

