//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.18408
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace CGME
{
	public abstract class ActionCondition : Action
	{
		private Action next_action;
		private bool wait = false;
		
		public Action NextAction{get{return next_action;}set{next_action = value;}}
		public bool Wait{get{return wait;}set{wait = value;}}
		
		public abstract bool Condition();
		
		public override bool Effect(){
			
			if (Condition()){
				next_action.Run ();
				return true;
			}
				
			return false;
		}
		
		public override void Enable(bool enable){
			
			this.enabled = enable;
			
			EnableResources(enable);
			
			next_action.Enable(enable);
		}
		
		public override void Arm(){
					
			armed = true;
			next_action.Arm();
		}
		
		public override void Disarm(){
			armed = false;
			next_action.Disarm();
		}
		
		
	}
}

