//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.18408
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace CGME
{
	public abstract class Action : Actor
	{
		protected bool armed = true;
		
		public bool IsArmed{get{return armed;}}
		
		public GameManager manager;

		public bool Run(){
		
			manager = GameManager.GetInstance();
						
			if (Enabled && armed){
							
				if (Effect()){
					Disarm ();
					return true;
				}
			}
			
			return false;
		}
		
		public abstract void Arm();
		public abstract void Disarm();
		public abstract bool Effect();
		
		public abstract void Enable(bool enabled);
		
		public Actor FindActor(string actor_name){
			
			if (this.Name == actor_name) return this;
					
			return null;
		}
	}
	

	
	
}

