//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.18408
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;

namespace CGME
{
	public class ActionGroup : Action
	{
		private List<Action> actions = new List<Action>();
		
		public ActionGroup ()
		{
		}
		
		// GET/SET FUNCIONS -----------------------------------------
		
		public CGME.Action GetAction(CGME.Action _action)
		{
			foreach (Action action in actions) {
				if (action == _action)
					return action;
			}
			return null;
		}
		
		public CGME.Action GetCard(string name)
		{
			foreach (Action action in actions) {
				if (action.Name == name)
					return action;
			}
			return null;
		}
		
		public Action GetAction(int index){
			return actions[index];
		}
		
		public int Actions_Size{
			get { return actions.Count;}
		}
		
		// LIST FUNCTIONS ------------------------------------------
		
		public Action AddAction(CGME.Action action){
			actions.Add(action);
			return action;
		}
		
		public void RemoveAction(int index){
			actions.RemoveAt(index);
		}
		
		public void RemoveAction(CGME.Action action){
			actions.Remove(action);
		}
		
		public void ClearActions(){
			actions.Clear();
		}
		
		// 	PUBLIC FUNCTIONS
		
		public override bool Effect(){
			
			foreach(Action action in actions){
				action.Run ();
			}
			
			return true;
		}
		
		public override void Enable(bool enable){
			
			this.enabled = enable;
			
			EnableResources(enable);
			
			foreach (Action action in actions){
				action.Enable(enable);
			}
			
		}
		
		public override void Arm(){
			this.armed = true;
			foreach(Action action in actions){
				action.Arm ();
			}
		}
		
		public override void Disarm(){
			this.armed = false;
			foreach(Action action in actions){
				action.Disarm ();
			}
		}
		
	}
}

