//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.544
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using UnityEngine;
namespace CGME
{
//	public class Factory
//	{
//		public Factory ()
//		{
//		}
//
//		public static CGME.Game BuildGame(){
//			return new CGME.Game();
//		} 
//
//		public static CGME.Ruleset BuildRuleset(string name, bool enabled = true){
//			CGME.Ruleset ruleset = new CGME.Ruleset(name);
//			ruleset.Enabled = enabled;
//
//			return ruleset;
//		}
//
//		public static CGME.Phase BuildPhase(string name, bool enabled = true){
//			CGME.Phase phase = new CGME.Phase(name);
//			phase.Enabled = enabled;
//
//			return phase;
//		}
//
//		public static CGME.Action BuildAction1(string name, bool enabled = true){
//
//				StandardAction action = new CGME.StandardAction(name);
//				action.Enabled = enabled;
//				return action;
//			}
//
//		public static CGME.Action BuildAction2(string name, bool enabled = true){
//
//			EndPhaseAction action = new CGME.EndPhaseAction(name);
//			action.Enabled = enabled;	
//			return action;
//		}
//
//		public static CGME.Action BuildGroupAction(string name, bool enabled = true){
//			GroupAction action = new CGME.GroupAction(name);
//			action.Enabled = enabled;
//			return action;
//		}
//
//
//		public static CGME.Player BuildPlayer(string name, bool enabled = true){
//			CGME.Player player = new CGME.Player(name);
//			player.Enabled = enabled;
//
//			return player;
//		}
//
//		public static CGME.Deck BuildDeck(string name, bool enabled = true){
//			CGME.Deck deck = new CGME.Deck(name);
//			deck.Enabled = enabled;
//
//			return deck;
//		}
//
//		public static CGME.Card BuildCard(string name, bool enabled =  true){
//			CGME.Card card = new CGME.Card(name);
//			card.Enabled = enabled;
//
//			return card;
//		}
//
//		public static CGME.Resource<int> BuildIntResource(string name, bool enabled = true){
//
//			CGME.Resource<int> resource = new CGME.Resource<int>(name);
//			resource.Enabled = enabled;
//			return resource;
//		}
//
//		public static CGME.Resource<float> BuildFloatResource(string name, bool enabled = true){
//
//			CGME.Resource<float> resource = new CGME.Resource<float>(name);
//			resource.Enabled = enabled;
//			return resource;
//		}
//
//		public static CGME.Resource<string> BuildStringResource(string name, bool enabled = true){
//			
//			CGME.Resource<string> resource = new CGME.Resource<string>(name);
//			resource.Enabled = enabled;
//			return resource;
//		}
//
//	}


}

