//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.544
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace CGME
{
	public class Resource : CGME.Actor
	{
		//TODO Implement generic value
		//private T value;
	
		public Resource(){

		}
		public Resource(string name){
			Name = name;
			Enabled = false;
		}

		//public T getValue(){
		//	return value;
		//}



	}

	public class Resource<T> : CGME.Resource
	{
		private T _value;

		public Resource(){

		}

		public Resource(string name, T value, bool enabled = true){

			this.Name = name;
			this.Value = value;
			this.Enabled = enabled;

		}

		public T Value{
			get{return _value;}
			set{_value = value;}
		}
	}
}

